### ISSUE TITLE
Disable root login via SSH

### ISSUE THREAD

**Issue by xzavrel** [valouseko/ansible_data#3]
- [x] Na každý stroj si vytvoř nového uživatele pomocí kterého se budeš přihlašovat
- [x] Pomocí Ansible zakaž přihlašování uživatele root pomocí ssh

Hint pro zakázání přihlašování root uživatele
```
- name: "Disable root login via SSH"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
  notify:
    - "Restart sshd"
 ```
